# Generated by Django 5.1 on 2024-08-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(default="Optional", max_length=20),
        ),
    ]
