# Generated by Django 5.1 on 2024-08-13 00:12

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="addmission_no",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Others"),
                    ("P", "Prefer Not To Say"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="StudenFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_until", models.DateField(default=students.models.next_month)),
                ("total_amount", models.PositiveIntegerField(default=0)),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                ("receipt_generated", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
