# Generated by Django 5.1 on 2024-08-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_addmission_no_alter_student_address_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudenFee",
            new_name="StudentFee",
        ),
    ]
