# Generated by Django 5.1 on 2024-08-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_rename_studenfee_studentfee"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
