# Generated by Django 5.1 on 2024-08-13 01:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["course_name"]},
        ),
        migrations.AddField(
            model_name="course",
            name="course_code",
            field=models.CharField(default="DEFAULT CODE", max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name="course",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_description",
            field=models.TextField(blank=True),
        ),
    ]
