# Generated by Django 5.1 on 2024-08-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_options_course_course_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(default="DEFAULT CODE", max_length=12, unique=True),
        ),
    ]
